/*
 * application
 */
export const APPLICATION_ROOT_CHANGED = 'APPLICATION_ROOT_CHANGED';

/*
 * current user
 */
export const CURRENT_USER_REGISTER = 'CURRENT_USER_REGISTER';
export const CURRENT_USER_REGISTER_FINISH = 'CURRENT_USER_REGISTER_FINISH';

export const CURRENT_USER_FORGOT_PASS = 'CURRENT_USER_FORGOT_PASS';

export const CURRENT_USER_LOGIN = 'CURRENT_USER_LOGIN';
export const CURRENT_USER_LOGIN_FINISH = 'CURRENT_USER_LOGIN_FINISH';
export const CURRENT_USER_LOGIN_FACEBOOK = 'CURRENT_USER_LOGIN_FACEBOOK';
export const CURRENT_USER_LOGIN_GOOGLE = 'CURRENT_USER_LOGIN_GOOGLE';
export const CURRENT_USER_LOGIN_ACCOUNT_KIT = 'CURRENT_USER_LOGIN_ACCOUNT_KIT';
export const CURRENT_USER_LOGOUT = 'CURRENT_USER_LOGOUT';

export const CURRENT_USER_GET_PROFILE = 'CURRENT_USER_GET_PROFILE';
export const CURRENT_USER_GET_PROFILE_FINISH =
  'CURRENT_USER_GET_PROFILE_FINISH';
export const CURRENT_USER_UPDATE_PROFILE = 'CURRENT_USER_UPDATE_PROFILE';
export const CURRENT_USER_UPDATE_PROFILE_FINISH =
  'CURRENT_USER_UPDATE_PROFILE_FINISH';

export const CURRENT_USER_UPLOAD_IMAGE = 'CURRENT_USER_UPLOAD_IMAGE';

export const CURRENT_USER_GET_LIST_LIKE = 'CURRENT_USER_GET_LIST_LIKE';
export const CURRENT_USER_GET_LIST_LIKE_FINISH =
  'CURRENT_USER_GET_LIST_LIKE_FINISH';
export const CURRENT_USER_GET_LIST_LIKE_RESET =
  'CURRENT_USER_GET_LIST_LIKE_RESET';
export const CURRENT_USER_ADD_LIST_LIKE = 'CURRENT_USER_ADD_LIST_LIKE';
export const CURRENT_USER_SET_LIST_LIKE = 'CURRENT_USER_SET_LIST_LIKE';

export const CURRENT_USER_GET_LIST_CHAT = 'CURRENT_USER_GET_LIST_CHAT';
export const CURRENT_USER_GET_LIST_CHAT_FINISH =
  'CURRENT_USER_GET_LIST_CHAT_FINISH';
export const CURRENT_USER_GET_LIST_CHAT_RESET =
  'CURRENT_USER_GET_LIST_CHAT_RESET';
export const CURRENT_USER_GET_LIST_CHAT_RESET_FINISH =
  'CURRENT_USER_GET_LIST_CHAT_RESET_FINISH ';
export const CURRENT_USER_GET_LIST_CHAT_DEL = 'CURRENT_USER_GET_LIST_CHAT_DEL';
export const CHAT_GET_DETAIL = 'CHAT_GET_DETAIL';
export const CHAT_GET_DETAIL_FINISH = 'CHAT_GET_DETAIL_FINISH';
export const CHAT_SENT_MESSAGE = 'CHAT_SENT_MESSAGE';
export const SOCKET_CHAT_CREATE_POST = 'SOCKET_CHAT_CREATE_POST';
export const SOCKET_CHAT_CHANGE_STATE = 'SOCKET_CHAT_CHANGE_STATE';
export const SOCKET_CHAT_CHANGE_ONLINE = 'SOCKET_CHAT_CHANGE_ONLINE';
export const CURRENT_USER_GET_LIST_USER_WAIT =
  'CURRENT_USER_GET_LIST_USER_WAIT';
export const CURRENT_USER_GET_LIST_USER_WAIT_FINISH =
  'CURRENT_USER_GET_LIST_USER_WAIT_FINISH';
export const SET_ID_ACTIVE_CHAT = 'SET_ID_ACTIVE_CHAT';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const SOCKET_CHAT_CREATE_POST_MY_ID = 'SOCKET_CHAT_CREATE_POST_MY_ID';
export const ADD_ITEM_LIST_CHAT = 'ADD_ITEM_LIST_CHAT';
export const REMOVE_ITEM_WITH_ID = 'REMOVE_ITEM_WITH_ID';

export const SEARCH_USER_GET = 'SEARCH_USER_GET';
export const SEARCH_USER_GET_FINISH = 'SEARCH_USER_GET_FINISH';
export const SEARCH_USER_REMOVE = 'SEARCH_USER_REMOVE';
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';

export const QUESTTION_GET = 'QUESTTION_GET';
export const QUESTTION_GET_FINISH = 'QUESTTION_GET_FINISH';
export const USER_SET_LIKE_STATUS = 'USER_SET_LIKE_STATUS';
