export const NAMEAPP = 'app';
export const CURRENT_USER_LOGOUT = 'CURRENT_USER_LOGOUT';
export const CURRENT_USER_REGISTER_FINISH = 'CURRENT_USER_REGISTER_FINISH';
export const CURRENT_USER_LOGIN_FINISH = 'CURRENT_USER_LOGIN_FINISH';
export const CURRENT_USER_GET_PROFILE_FINISH =
  'CURRENT_USER_GET_PROFILE_FINISH';
export const CURRENT_USER_UPDATE_PROFILE_FINISH =
  'CURRENT_USER_UPDATE_PROFILE_FINISH';
